// <auto-generated />
using System;
using GotSeries.Api.Service.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotSeries.Api.Service.Migrations
{
    [DbContext(typeof(GotDbContext))]
    partial class GotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountAttackerSoldiers")
                        .HasColumnType("int");

                    b.Property<int>("AmountDefenderSoldiers")
                        .HasColumnType("int");

                    b.Property<bool>("AttackerWon")
                        .HasColumnType("bit");

                    b.Property<int?>("BattleTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasMayorCapture")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMayorDeath")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Battles_Id");

                    b.HasIndex("BattleTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleCommander", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("CommanderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttacker")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_BattleCommanders_Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CommanderId");

                    b.ToTable("BattleCommanders");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttacker")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_BattleHouses_Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("HouseId");

                    b.ToTable("BattleHouses");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleKing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttacker")
                        .HasColumnType("bit");

                    b.Property<int?>("KingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_BattleKings_Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("KingId");

                    b.ToTable("BattleKings");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BattleType1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BattleType");

                    b.HasKey("Id")
                        .HasName("PK_BattleTypes_Id");

                    b.ToTable("BattleTypes");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("NroInSeason")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("OriginalDateAir")
                        .HasColumnType("date");

                    b.Property<byte>("SeasonId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("UsViewers")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK_Chapters_Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCommander")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeath")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHuman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsKing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoyalty")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Characters_Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Death", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegiance")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("DeathCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DeathCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("DeathDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("KilledId")
                        .HasColumnType("int");

                    b.Property<int?>("KillerId")
                        .HasColumnType("int");

                    b.Property<string>("LocationComments")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_Deaths_Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("DeathCategoryId");

                    b.HasIndex("KilledId");

                    b.HasIndex("KillerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Deaths");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.DeathCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_DeathCategories_Id");

                    b.ToTable("DeathCategories");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoatOfArmsUrl")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Houses_Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Kingdoms_Id");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("Location1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Location");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Locations_Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_People_Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Season", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Seasons_Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleType", "BattleType")
                        .WithMany("Battles")
                        .HasForeignKey("BattleTypeId")
                        .HasConstraintName("FK_Battles_BattleTypeId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany("Battles")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_Battles_LocationId");

                    b.Navigation("BattleType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleCommander", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", "Battle")
                        .WithMany("BattleCommanders")
                        .HasForeignKey("BattleId")
                        .IsRequired()
                        .HasConstraintName("FK_BattleCommanders_BattleId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", "Commander")
                        .WithMany("BattleCommanders")
                        .HasForeignKey("CommanderId")
                        .IsRequired()
                        .HasConstraintName("FK_BattleCommanders_CommanderId");

                    b.Navigation("Battle");

                    b.Navigation("Chapter");

                    b.Navigation("Commander");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleHouse", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", "Battle")
                        .WithMany("BattleHouses")
                        .HasForeignKey("BattleId")
                        .IsRequired()
                        .HasConstraintName("FK_BattleHouses_BattleId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.House", "House")
                        .WithMany("BattleHouses")
                        .HasForeignKey("HouseId")
                        .IsRequired()
                        .HasConstraintName("FK_BattleHouses_HouseId");

                    b.Navigation("Battle");

                    b.Navigation("House");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleKing", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", "Battle")
                        .WithMany("BattleKings")
                        .HasForeignKey("BattleId")
                        .IsRequired()
                        .HasConstraintName("FK_BattleKings_BattleId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", "King")
                        .WithMany("BattleKings")
                        .HasForeignKey("KingId")
                        .HasConstraintName("FK_BattleKings_KingId");

                    b.Navigation("Battle");

                    b.Navigation("Chapter");

                    b.Navigation("King");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Season", "Season")
                        .WithMany("Chapters")
                        .HasForeignKey("SeasonId")
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_SeasonId");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Death", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", "Chapter")
                        .WithMany("Deaths")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_Deaths_ChapterId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.DeathCategory", "DeathCategory")
                        .WithMany("Deaths")
                        .HasForeignKey("DeathCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Deaths_DeathCategoryId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", "Killed")
                        .WithMany("DeathKilleds")
                        .HasForeignKey("KilledId")
                        .IsRequired()
                        .HasConstraintName("FK_Deaths_KilledId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", "Killer")
                        .WithMany("DeathKillers")
                        .HasForeignKey("KillerId")
                        .HasConstraintName("FK_Deaths_KillerId");

                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany("Deaths")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_Deaths_LocationId");

                    b.Navigation("Chapter");

                    b.Navigation("DeathCategory");

                    b.Navigation("Killed");

                    b.Navigation("Killer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.House", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Kingdom", "Kingdom")
                        .WithMany("Houses")
                        .HasForeignKey("KingdomId")
                        .HasConstraintName("FK_Houses_KingdomId");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Location", b =>
                {
                    b.HasOne("GotSeries.Api.Service.Infrastructure.Data.Entities.Kingdom", "Kingdom")
                        .WithMany("Locations")
                        .HasForeignKey("KingdomId")
                        .HasConstraintName("FK_Locations_KingdomId");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Battle", b =>
                {
                    b.Navigation("BattleCommanders");

                    b.Navigation("BattleHouses");

                    b.Navigation("BattleKings");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.BattleType", b =>
                {
                    b.Navigation("Battles");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Chapter", b =>
                {
                    b.Navigation("Deaths");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Character", b =>
                {
                    b.Navigation("BattleCommanders");

                    b.Navigation("BattleKings");

                    b.Navigation("DeathKilleds");

                    b.Navigation("DeathKillers");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.DeathCategory", b =>
                {
                    b.Navigation("Deaths");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.House", b =>
                {
                    b.Navigation("BattleHouses");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Kingdom", b =>
                {
                    b.Navigation("Houses");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Location", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Deaths");
                });

            modelBuilder.Entity("GotSeries.Api.Service.Infrastructure.Data.Entities.Season", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
